version: '3.9'

services:
    nginx:
        build:
            context: .
            dockerfile: dockerfiles/nginx/Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/app
        links:
            - php-fpm
    php-fpm:
        build:
            context: .
            dockerfile: dockerfiles/php-fpm/Dockerfile
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app

    mysql:
        image: mysql:8
        ports:
            - ${DB_PORT:-3306}:${DB_PORT:-3306}
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./dockerfiles/mysql/data:/var/lib/mysql
